---
version: '3.4'
services:
  ci-infra:
    &ci-infra
    volumes:
      - $HOME/.config/gcloud:/root/.config/gcloud
      - .:/go-pubsub
    working_dir: /go-pubsub
    build:
      context: .
      target: ci-infra

  go-ci:
    &go-ci
    volumes:
      - .:/go-pubsub
    working_dir: /go-pubsub
    build:
      context: .
      target: go-ci

  gcloud:
    <<: *ci-infra
    entrypoint: gcloud

  terraform:
    <<: *ci-infra
    entrypoint: terraform

  go-sh: 
    <<: *go-ci
    #use default entrypoint
    environment:
      CGO_ENABLED: 0

  go-lint:
    <<: *go-ci
    entrypoint: golangci-lint
    environment:
      CGO_ENABLED: 0
      GOROOT: /usr/local/go # re: https://github.com/golangci/golangci-lint/issues/3107 bumping to 1.49.0 worked but will keep this env.
