---
version: '3.4'
services:
  base:
    &base
    volumes:
      - $HOME/.config/gcloud:/root/.config/gcloud
      - .:/go-pubsub
    working_dir: /go-pubsub
    build:
      context: .
      target: ci

  gcloud:
    <<: *base
    entrypoint: gcloud

  terraform:
    <<: *base
    entrypoint: terraform
