run:
  concurrency: 15
  timeout: 5m
  issues-exit-code: 2
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dupl
    - gofmt
    - goimports
  fast: false