name: go-pubsub-order-lint-and-test 
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: tf fmt check
      run: |
        ./scripts/lint.sh tf_fmt

    - name: validate tf
      run: |
        ./scripts/lint.sh tf_validate

    - name: lint go
      run: |
        ./scripts/lint.sh lint_go
